[project]
name = "cf-lia-data-science"
version = "0.1.0"
description = "Ciencia de Datos con Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.2.5",
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "pyarrow>=17.0.0",
    "seaborn>=0.13.2",
]
