project:
  type: book

book:
  title: "Análisis Inicial de Datos"
  author: "Francisco Palm"
  date: "2024-10-09"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - about.qmd
    search: true
  sidebar: 
    logo: "images/logo_fpalm.png"
  chapters:
    - index.qmd
    - intro.qmd
    - analisis_inicial.qmd
    - estructura.qmd
    - contenido.qmd
    - limpieza.qmd
    - atipicos.qmd
    - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    lang: es



